name: nust
description: Nust unofficial Student app

version: 2.0.7+29
publish_to: none

environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider_plus: ^7.0.0
  dio: ^5.5.0+1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  webview_flutter: ^4.8.0
  flutter_email_sender: ^6.0.3
  html: ^0.15.4 
  firebase_core: ^3.10.1 
  firebase_messaging: ^15.2.1
  url_launcher: ^6.3.0  
  connectivity_plus: ^6.0.5
  app_version_update: ^6.0.0
  custom_refresh_indicator: ^4.0.1
  cached_network_image: ^3.4.1
  local_auth: ^2.3.0
  encrypt_shared_preferences: ^0.8.7
  share_plus: ^10.1.4 
  confetti: ^0.8.0 
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.70.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  flutter_file_downloader: ^2.0.0
  path_provider: ^2.1.4
  device_info_plus: ^11.2.2
  flutter_downloader: ^1.11.8
  webview_cookie_manager:
    git:
      url: https://github.com/rekire/webview_cookie_manager.git
      ref: main
  background_downloader: ^8.5.3
  shimmer: ^3.0.0
  screenshot: ^3.0.0
  firebase_database: ^11.3.2
  quick_actions: ^1.1.0
   

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/lottie/
     - .env
     
flutter_native_splash:
  color: '#ffffff'
  color_dark: '#000000'
  image: assets/images/appLogo.png
  image_dark: assets/images/appLogo.png
  branding: assets/images/branding.png
  branding_dark: assets/images/branding_dark.png
  branding_mode: bottom
  android: true
  ios: true
  web: false

  android_12:
    color: '#ffffff'
    color_dark: '#000000'
    icon_background_color: '#ffffff'
    icon_background_color_dark: '#000000'
    branding: assets/images/branding_12.png
    branding_dark: assets/images/branding_dark_12.png
    branding_mode: bottom

